# Generated by Django 4.2 on 2023-04-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0002_alter_link_id_alter_link_type_alter_link_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="type",
            field=models.CharField(
                choices=[
                    ("blog", "Blog"),
                    ("project", "Project"),
                    ("docs", "Documentation"),
                    ("feed", "Feed"),
                    ("podcast", "Podcast"),
                    ("site", "Site"),
                    ("git", "Git-repo"),
                    ("forum", "Forum"),
                    ("forum-post", "Forum-post"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="url",
            field=models.URLField(db_index=True, max_length=1024),
        ),
    ]
